{% set name = "magic-cta-pipe" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/magic_cta_pipe-{{ version }}.tar.gz
  sha256: 732f60a84a4b0eae218e649153bb6fc35cd743e5890ce7ea07cc96dfb7107df9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - create_dl3_index_files = magicctapipe.scripts.lst1_magic.create_dl3_index_files:main
    - lst1_magic_create_irf = magicctapipe.scripts.lst1_magic.lst1_magic_create_irf:main
    - lst1_magic_dl1_stereo_to_dl2 = magicctapipe.scripts.lst1_magic.lst1_magic_dl1_stereo_to_dl2:main
    - lst1_magic_dl2_to_dl3 = magicctapipe.scripts.lst1_magic.lst1_magic_dl2_to_dl3:main
    - lst1_magic_event_coincidence = magicctapipe.scripts.lst1_magic.lst1_magic_event_coincidence:main
    - lst1_magic_mc_dl0_to_dl1 = magicctapipe.scripts.lst1_magic.lst1_magic_mc_dl0_to_dl1:main
    - lst1_magic_stereo_reco = magicctapipe.scripts.lst1_magic.lst1_magic_stereo_reco:main
    - lst1_magic_train_rfs = magicctapipe.scripts.lst1_magic.lst1_magic_train_rfs:main
    - magic_calib_to_dl1 = magicctapipe.scripts.lst1_magic.magic_calib_to_dl1:main
    - merge_hdf_files = magicctapipe.scripts.lst1_magic.merge_hdf_files:main
    - tune_magic_nsb = magicctapipe.scripts.lst1_magic.tune_magic_nsb:main
    - check_MAGIC_runs = magicctapipe.scripts.lst1_magic.semi_automatic_scripts.check_MAGIC_runs:main
    - coincident_events = magicctapipe.scripts.lst1_magic.semi_automatic_scripts.coincident_events:main
    - create_LST_table = magicctapipe.scripts.lst1_magic.semi_automatic_scripts.database_production.create_LST_table:main
    - dl1_production = magicctapipe.scripts.lst1_magic.semi_automatic_scripts.dl1_production:main
    - job_accounting = magicctapipe.scripts.lst1_magic.semi_automatic_scripts.job_accounting:main
    - list_from_h5 = magicctapipe.scripts.lst1_magic.semi_automatic_scripts.list_from_h5:main
    - lstchain_version = magicctapipe.scripts.lst1_magic.semi_automatic_scripts.database_production.lstchain_version:main
    - LSTnsb = magicctapipe.scripts.lst1_magic.semi_automatic_scripts.database_production.LSTnsb:main
    - merge_stereo = magicctapipe.scripts.lst1_magic.semi_automatic_scripts.merge_stereo:main
    - merging_runs = magicctapipe.scripts.lst1_magic.semi_automatic_scripts.merging_runs:main
    - nsb_level = magicctapipe.scripts.lst1_magic.semi_automatic_scripts.database_production.nsb_level:main
    - nsb_to_h5 = magicctapipe.scripts.lst1_magic.semi_automatic_scripts.database_production.nsb_to_h5:main
    - stereo_events = magicctapipe.scripts.lst1_magic.semi_automatic_scripts.stereo_events:main
    - update_MAGIC_database = magicctapipe.scripts.lst1_magic.semi_automatic_scripts.database_production.update_MAGIC_database:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - ctapipe>=0.25.0,<0.26
    - lstchain>=0.11.0
    - ctaplot >=0.6.4,<0.7.dev0
    - ctapipe-io-magic=0.5.7
    - gammapy=1.3
    - uproot >=5.0,<6.dev0
    - pandas
    - pyirf
    - seaborn
    - astropy-base
    - bokeh
    - eventio
    - h5py
    - iminuit >=2
    - joblib >=1.2.0,<1.3.dev0
    - matplotlib-base
    - numba
    - numpy
    - protozfits >=2.5,<3.dev0
    - scipy
    - scikit-learn
    - pytables
    - pymongo
    - pyparsing
    - jinja2 >=3.0.2,<3.1.dev0

test:
  imports:
    - magicctapipe
  commands:
    - pip check
    - python -c "from magicctapipe import __version__; print(__version__)"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cta-observatory/magic-cta-pipe
  summary: pipeline for the analysis of joint MAGIC+LST-1 data
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aleberti
    - Elisa-Visentin
    - jsitarek
